name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NCP_REGISTRY: argo-repo.kr.ncr.ntruss.com

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set dynamic image tag
      run: echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Log in to NCP Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.NCP_REGISTRY }}
        username: ${{ secrets.NCP_ACCESS_KEY }}
        password: ${{ secrets.NCP_SECRET_KEY }}

    - name: Build Docker Image
      run: |
        IMAGE=${{ env.NCP_REGISTRY }}/apache:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Push Docker Image
      run: docker push ${{ env.IMAGE }}

  update-yaml:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout GitOps Repository
      uses: actions/checkout@v3
      with:
        repository: "jyscode/ncp-argocd-yaml-repo"
        token: ${{ secrets.Argo_Repo }}
        path: gitops-repo

    - name: Update Deployment YAML
      run: |
        cd gitops-repo
        DEPLOYMENT_FILE=web/web.yaml
        sed -i "/image:/s|image:.*|image: ${{ env.IMAGE }}|" $DEPLOYMENT_FILE

        git config --global user.name "GitHub Actions"
        git config --global user.email "devops@company.com"
        git add $DEPLOYMENT_FILE
        git commit -m "Update image to ${{ env.IMAGE }}"
        git push origin main
