name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main  # main 브랜치에서 푸시될 때만 실행

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout source code
      uses: actions/checkout@v3

    # 2. Docker 레지스트리 로그인
    - name: Log in to NCP Registry
      uses: docker/login-action@v2
      env:
        NCP_REGISTRY: "registry 이름 기입"
      with:
        registry: ${{ env.NCP_REGISTRY }}
        username: ${{ secrets.NCP_ACCESS_KEY }}
        password: ${{ secrets.NCP_SECRET_KEY }}

    # 3. Docker 이미지 빌드
    - name: Build Docker Image
      env:
        NCP_REGISTRY: "registry 이름 기입"
      run: |
        IMAGE_NAME=${{ env.NCP_REGISTRY }}/apache
        IMAGE_TAG=8.0
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./web/
        echo "IMAGE=$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

    # 4. Docker 이미지 푸시
    - name: Push Docker Image
      run: |
        docker push ${{ env.IMAGE }}
        
  update-yaml:
    name: Update Kubernetes Manifest in GitOps Repo
    runs-on: ubuntu-latest
    needs: build-and-push  # Docker 이미지 빌드가 완료된 후 실행

    steps:
    # 1. GitOps 리포지토리 체크아웃
    - name: Checkout GitOps Repository
      uses: actions/checkout@v3
      with:
        repository: "gitops repo 기입"    # ArgoCD와 연결된 GitOps 리포지토리
        token: ${{ secrets.Argo_Repo }}  # GitHub Personal Access Token
        path: gitops-repo

    # 2. YAML 파일 업데이트
    - name: Update Deployment YAML
      env:
        NCP_REGISTRY: argo-repo.kr.ncr.ntruss.com
      run: |
        IMAGE_NAME=${{ env.NCP_REGISTRY }}/apache
        IMAGE_TAG=8.0
        IMAGE=$IMAGE_NAME:$IMAGE_TAG
        cd gitops-repo
        DEPLOYMENT_FILE=web/web.yaml
        
        # deployment.yaml의 image 필드를 새 이미지로 업데이트
        sed -i "/name: apache/ {n;s|image: .*|image: $IMAGE|}" $DEPLOYMENT_FILE
        
        # 변경 사항 커밋
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add $DEPLOYMENT_FILE
        git commit -m "Update image to $IMAGE"
        git push origin main  # 변경 사항 푸시
