name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NCP_REGISTRY: argo-repo.kr.ncr.ntruss.com
    outputs:
      IMAGE: ${{ steps.set-image.outputs.IMAGE }}

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout source code
      uses: actions/checkout@v3

    # 2. 동적 이미지 태그 생성
    - id: set-image
      name: Set dynamic image tag
      run: |
        IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}
        IMAGE=${{ env.NCP_REGISTRY }}/apache:$IMAGE_TAG
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
        echo "IMAGE=$IMAGE"

    # 3. Docker 레지스트리 로그인
    - name: Log in to NCP Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.NCP_REGISTRY }}
        username: ${{ secrets.NCP_ACCESS_KEY }}
        password: ${{ secrets.NCP_SECRET_KEY }}

    # 4. Docker 이미지 빌드
    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE }} .

    # 5. Docker 이미지 푸시
    - name: Push Docker Image
      run: docker push ${{ env.IMAGE }}

  update-yaml:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    # 1. GitOps 리포지토리 체크아웃
    - name: Checkout GitOps Repository
      uses: actions/checkout@v3
      with:
        repository: "jyscode/ncp-argocd-yaml-repo"  
        token: ${{ secrets.Argo_Repo }}
        path: gitops-repo

    # 2. Deployment YAML 이미지 업데이트
    - name: Update Deployment YAML
      run: |
        IMAGE=${{ needs.build-and-push.outputs.IMAGE }}
        cd gitops-repo
        DEPLOYMENT_FILE=web/web.yaml
        echo "Updating $DEPLOYMENT_FILE with $IMAGE"

        # image 줄 치환
        sed -i "s|image:.*|image: $IMAGE|" $DEPLOYMENT_FILE

        # git commit & push (변경 사항 없으면 commit 생략)
        git config --global user.name "GitHub Actions"
        git config --global user.email "devops@company.com"
        git add $DEPLOYMENT_FILE
        git diff --cached --quiet || git commit -m "Update image to $IMAGE"
        git push origin main
  update-private-git:
    name: Update NCP Private Git
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout GitOps Repository (NCP SourceCommit)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NCP_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan devtools.ncloud.com >> ~/.ssh/known_hosts

          git clone -b main \
            ssh://3503596_cloudjy0403_7baa5@devtools.ncloud.com:22/3503596/kjy-argo-repo.git \
            gitops-private
      - name: Check repo structure
        run: |
          ls -R gitops-private

      # YAML 업데이트
      - name: Update Deployment YAML
        run: |
          cd gitops-private/web
          DEPLOYMENT_FILE=web.yaml
          sed -i "s|image:.*|image: ${IMAGE}|" $DEPLOYMENT_FILE
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add $DEPLOYMENT_FILE
          git commit -m "Update image to ${IMAGE}" || echo "No changes to commit"
          git push origin main

